---
name: Cleanup Inactive Server Files
on:
  push:
  # schedule:
  #   - cron: '0 6 * * *' # Every day
  # workflow_dispatch:
  #  for domain in `curl http://127.0.0.1:3000/active-servers/ | tr '[",]' \ `; do echo $domain; done
permissions:
  contents: write
  pull-requests: write

env:
  TEST_FILE_PATH: ./servers/server.something.yml

          # echo "server_paths=$(gh repo read-dir servers --repo mastodon/server_directory_test --json name,path --jq '.["entries"]')" >> $GITHUB_OUTPUT
          # echo $server_paths
jobs:
  cleanup-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Read filenames in server dir
        id: file_path
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "server_domains=$(gh repo read-dir servers --repo mastodon/server_directory_test --json name | jq -r '.["entries"] | .[] | .name' | xargs -I {} basename {} .yml | xargs -I {} basename {} .yaml | xargs)" >> $GITHUB_OUTPUT
          echo $server_domains

      # - name: echo server-paths
      #   run: echo "${{ steps.file_path.outputs.server_paths }}"
      - name: echo server-domains
        run: echo "${{ steps.file_path.outputs.server_domains }}"
      - name: Request active server files
        id: files
        # filter out which items from the second list are missing from the base list
        run: |
          ACTIVE_SERVERS="add.more.languages allows.all.languages catland.social european.server for.testing loony.tunes mastodon.social mstdn.srvr other.server server.something test.server"
          DOMAINS="${{ steps.file_path.outputs.server_domains }}"
          MISS=$(grep -vxf <(echo "$ACTIVE_SERVERS" | tr ' ' '\n') <(echo "$DOMAINS" | tr ' ' '\n') || true)
          MISSING=$(echo "$MISS" | tr '\n' ' ')
          echo "missing_domains=$MISSING" >> $GITHUB_OUTPUT

          if [ -z "$MISSING" ]; then
            echo "all elements from server domains are in ACTIVE_SERVERS"
          else
            echo "missing elements $MISSING"
          fi
        shell: bash
      - name: echo missing-domains
        run: echo "${{ steps.files.outputs.missing_domains }}"
      - name: Remove Test file
        if: ${{ steps.files.outputs.missing_domains != '' }}
        run: |
          MISSING="${{ steps.files.outputs.missing_domains }}"

          for domain in $MISSING; do
            path="./servers/$domain"
            if [ -f  $path ]; then
              rm $path
              echo "Test file removed."
            else
              echo "$path not fund."
              exit  1
            fi
          done
        shell: bash
      # Create or update the pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: Remove inactive server files
          title: Cleanup Server Files (automated)
          author: GitHub Actions <noreply@github.com>
          body: Remove inactive server files, automated with GitHub Actions
          branch: cleanup-servers
          base: main
