---
name: Opt-in check
on:
  push:

jobs:
  Schema-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Get Changed Default Servers
        id: getfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FILES=$(gh pr diff ${{ github.event.pull_request.number }} --name-only | grep '^default_servers/' | xargs -I {} basename {} .yaml | xargs)
          echo "files=$FILES" >> $GITHUB_OUTPUT

      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: Request Opt-in file
        if: ${{ steps.getfile.outputs.files != '' }}
        shell: bash
        run: |
            FILES="${{ steps.getfile.outputs.files }}"
            for domain in $FILES; do
              RESPONSE_CODE=$(curl --silent --connect-timeout 5 --output /dev/null -I --write-out "%{http_code}" "http://${domain}/dsr_opt_in.txt" || echo "000")
              echo "Domain: $domain Statuscode: $RESPONSE_CODE"

              if [ "$RESPONSE_CODE" -ne 301 ]; then
                echo "$domain is not reachable"
                FAILED=$((FAILED + 1))
              else
                echo "$domain exists and is reachable"
              fi
            done

            if [ "$FAILED" -gt 0 ]; then
              echo "not all endpoint could be reached"
              exit 1
            fi
