---
name: Opt-in check
on:
  push:

jobs:
  Schema-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Get Changed Default Servers
        id: getfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FILES=$(gh pr diff ${{ github.event.pull_request.number }} --name-only | grep '^default_servers/' | xargs -I {} basename {} .yaml | xargs)
          echo "files=$FILES" >> $GITHUB_OUTPUT

      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: Request Opt-in file
        if: ${{ steps.getfile.outputs.files != '' }}
        run: |
            FILES="${{ steps.getfile.outputs.files }}"
            for domain in $FILES; do
              echo "Domain: $domain"
            done
            echo "results=$RESPONSE_CODE" >> GITHUB_OUTPUT

      - name: echo codes
        run: |
          echo ${{ steps.getfile.outputs.results }}
