name: PR Check schema
on: [push]

jobs:
  Schema-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs)"

      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: Install check-jsonschema
        run: pip install check-jsonschema

      - name: Run Check-jsonschema
        run: check-jsonschema --schemafile .schema.yml ${{ steps.getfile.outputs.files }}

  Lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Lint yaml files
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ${{ steps.getfile.outputs.files }}
          format: github
